# Generated by Django 6.0.5 on 2026-05-20 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_drug_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2027, 10, 2, 17, 43, 54, 571028, tzinfo=datetime.timezone.utc)),
        ),
    ]
