# Generated by Django 6.0.5 on 2026-05-20 18:44

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_drug_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateField(default=inventory.models.Drug.default_expiry),
        ),
    ]
